# config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false  # Изменено с true на false
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Quiz:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Model/Quiz/Entity'
                prefix: 'App\Model\Quiz\Entity'
                alias: Quiz
        controller_resolver:
            auto_mapping: false
        dql:
            string_functions:
                RANDOM: App\Functions\RandomFunction
