security:
    providers:
        app_user_provider:
            entity:
                class: App\Model\User\Entity\User
                property: username

    firewalls:
        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\UsernameAuthenticator

            entry_point: App\Security\UsernameAuthenticator

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/., roles: IS_AUTHENTICATED_FULLY }
